### PR TITLE
Add text option for Stopping your work

### LINKED ISSUE #4: Option for adding text in "What is stopping me from doing my work?"
Currently the question `What is stopping me from doing my work?` is hardcoded. Instead can ew ask this on the extension itself??

I would like to work on this

### PR DESCRIPTION
**Pull request by S2606**
Fixes #4 

screenshot from 2017-10-28 16-16-27

### CODE REVIEW

**Comment by S2606** [comment]
@hkedia321 Please review

**Comment by S2606** [comment]
@hkedia321 Done

**Comment by hkedia321** [comment]
@S2606 Unfortunately there were some merge conflicts. Please rebase and solve conflicts.

**Comment by S2606** [comment]
@hkedia321 During rebase it isnt detecting any file changes.

scrum_report

**Comment by S2606** [comment]
@hkedia321 Done

**Comment by S2606** [comment]
You r welcome @hkedia321

**Pull request merged**
